# Generated by Django 2.0.5 on 2019-07-02 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service', models.CharField(choices=[('initial-visit', 'initial visit'), ('repeat-visit', 'repeat visit')], default='initial-visit', max_length=32)),
                ('questionnaire_id', models.BigIntegerField(null=True)),
                ('questionnaire_answers_id', models.BigIntegerField(null=True)),
                ('consent_to_telehealth', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_visits', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
