# Generated by Django 2.0.5 on 2019-07-04 02:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.CharField(choices=[('initial-visit', 'initial visit'), ('repeat-visit', 'repeat visit')], max_length=32)),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='emr.Questionnaire')),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='questionnaire_answers_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.QuestionnaireAnswers'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='questionnaire_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.Questionnaire'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('service', 'version')},
        ),
    ]
