# Generated by Django 2.0.5 on 2019-07-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_auto_20190704_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='questionnaire_id',
            new_name='questionnaire',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='questionnaire_answers_id',
            new_name='questionnaire_answers',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='created',
            new_name='created_datetime',
        ),
    ]
