# Generated by Django 2.0.5 on 2019-07-09 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0003_auto_20190708_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('store_name', models.CharField(max_length=64)),
                ('address_line1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AK', 'Alaska'), ('HI', 'Hawaii'), ('AS', 'American Samoa'), ('GU', 'Guam'), ('MP', 'Northern Mariana Islands'), ('PR', 'Puerto Rico'), ('VI', 'Virgin Islands'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific')], max_length=128, null=True)),
                ('postal_code', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('primary_phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True)),
                ('primary_fax', localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Display Name')),
                ('exact_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Exact Name')),
                ('prescription_type', models.TextField()),
                ('rxcui', models.CharField(max_length=128)),
                ('days_supply', models.IntegerField()),
                ('refills', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('directions', models.TextField()),
                ('pharmacy_notes', models.TextField()),
                ('dispense_unit_id', models.BigIntegerField()),
                ('dosespot_id', models.BigIntegerField()),
                ('prescribed_datetime', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='emr.Pharmacy')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Eligibility Verified', 'eligibility verified'), ('Ineligible', 'ineligible'), ('Consent Accepted', 'consent accepted'), ('Questionnaire Completed', 'questionnaire completed'), ('Photos Uploaded', 'photos uploaded'), ('Provider Pending Action', 'provider pending'), ('Provider Awaiting User Input', 'provider awaiting user input'), ('Provider Signed', 'provider signed'), ('Provider Rx Submitted', 'provider rx submitted'), ('Provider Rx Denied', 'provider rx denied'), ('Provider Cancelled', 'provider cancelled')], default='Pending', max_length=32, verbose_name='Medical visit status'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='emr.Visit'),
        ),
    ]
