# Generated by Django 2.0.5 on 2019-07-09 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0004_auto_20190709_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_notes', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
