# Generated by Django 2.0.5 on 2019-07-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescriptionType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='type',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]