# Generated by Django 2.0.5 on 2019-07-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_auto_20190716_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit')], max_length=32),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit')], default='Initial Visit', max_length=32),
        ),
    ]