# Generated by Django 2.0.5 on 2019-07-19 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0009_auto_20190717_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaireanswers',
            old_name='created',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='questionnaireanswers',
            old_name='last_modified',
            new_name='last_modified_datetime',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]