# Generated by Django 2.0.5 on 2019-07-19 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0010_auto_20190719_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedPrescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_datetime', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='emr.Pharmacy')),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dispense_unit_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescribed_datetime',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescriptionType',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_type',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='type',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='visit',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosespot_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescribedprescriptions',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.Prescription'),
        ),
        migrations.AddField(
            model_name='prescribedprescriptions',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescribedprescriptions',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='emr.Visit'),
        ),
        migrations.AlterField(
            model_name='prescribedprescriptions',
            name='prescribed_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
