# Generated by Django 2.0.5 on 2019-07-21 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0011_auto_20190719_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescribedPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prescribed_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dosespot_id', models.BigIntegerField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='emr.Pharmacy')),
            ],
        ),
        migrations.RemoveField(
            model_name='prescribedprescriptions',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescribedprescriptions',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='prescribedprescriptions',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescribedprescriptions',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='prescribedprescriptions',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosespot_id',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='PrescribedPrescriptions',
        ),
        migrations.AddField(
            model_name='prescribedprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emr.Prescription'),
        ),
        migrations.AddField(
            model_name='prescribedprescription',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescribedprescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='emr.Visit'),
        ),
    ]
