# Generated by Django 2.0.5 on 2019-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0012_auto_20190721_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sappira_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='sappira_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescribedprescription',
            name='sappira_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sappira_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireanswers',
            name='sappira_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='sappira_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sappira_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
