
# Generated by Django 2.0.5 on 2019-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0014_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='uuid',
        )
    ]