# Generated by Django 2.0.5 on 2019-07-24 22:44

import dearbrightly.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0015_auto_20190723_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sappira_id', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_file', models.FileField(storage=dearbrightly.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('photo_type', models.CharField(choices=[('Front of face', 'front face'), ('Right side of face', 'right face'), ('Left side of face', 'left face'), ('Government-issued ID', 'photo id')], default='Front of face', max_length=32, verbose_name='Photo type')),
                ('photo_verified', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='emr.Visit')),
            ],
        )
    ]
