# Generated by Django 2.0.5 on 2019-07-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0016_auto_20190724_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_verified',
            new_name='photo_rejected',
        ),
    ]
