# Generated by Django 2.0.5 on 2019-07-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0018_auto_20190726_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Eligibility Verified', 'eligibility verified'), ('Ineligible', 'ineligible'), ('Consent Accepted', 'consent accepted'), ('Questionnaire Completed', 'questionnaire completed'), ('Photos Uploaded', 'photos uploaded'), ('Provider Pending Action', 'provider pending'), ('Provider Awaiting User Input', 'provider awaiting user input'), ('Provider Signed', 'provider signed'), ('Provider Rx Submitted', 'provider rx submitted'), ('Provider Rx Denied', 'provider rx denied'), ('Provider Cancelled', 'provider cancelled'), ('Pending Messages', 'pending messages')], default='Pending', max_length=32, verbose_name='Medical visit status'),
        ),
    ]
