# Generated by Django 2.0.5 on 2019-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0019_auto_20190726_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireanswers',
            name='sappira_question_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='last_modified_datetime',
            field=models.DateTimeField(),
        ),
    ]
