# Generated by Django 2.0.5 on 2019-08-02 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0020_auto_20190802_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrescribedPrescription',
            new_name='PatientPrescription',
        ),
    ]
