# Generated by Django 2.0.5 on 2019-08-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0021_auto_20190802_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprescription',
            name='status',
            field=models.CharField(choices=[('Initiated', 'initiated'), ('eRxSent', 'erx sent'), ('Error', 'error')], default='Initiated', max_length=32, verbose_name='Patient prescription status'),
        ),
    ]
