# Generated by Django 2.0.5 on 2019-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0024_auto_20190807_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('Front of face', 'front face'), ('Selfie and ID', 'selfie and id'), ('Right side of face', 'right face'), ('Left side of face', 'left face'), ('Government-issued ID', 'photo id')], default='Front of face', max_length=32, verbose_name='Photo type'),
        ),
    ]
