# Generated by Django 2.0.5 on 2019-08-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0025_auto_20190813_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit'), ('Wrinkle reduction', 'wrinkle reduction')], max_length=32),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit'), ('Wrinkle reduction', 'wrinkle reduction')], default='Initial Visit', max_length=32),
        ),
    ]
