# Generated by Django 2.0.5 on 2019-08-19 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0025_auto_20190813_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('Front of face', 'front face'), ('Right side of face', 'right face'), ('Left side of face', 'left face'), ('Government-issued ID', 'photo id')], default='Front of face', max_length=32, verbose_name='Photo type'),
        ),
    ]
