# Generated by Django 2.0.5 on 2019-08-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0026_auto_20190815_1039'),
        ('emr', '0026_auto_20190819_1112'),
    ]

    operations = [
    ]
