# Generated by Django 2.0.5 on 2019-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0027_merge_20190819_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit')], max_length=32),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit')], default='Initial Visit', max_length=32),
        ),
    ]
