# Generated by Django 2.0.5 on 2019-09-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0030_auto_20190924_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='dosespot_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
