# Generated by Django 2.0.5 on 2019-10-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0032_auto_20190927_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosespot_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
