# Generated by Django 2.0.5 on 2019-10-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0033_prescription_dosespot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='emr.Visit'),
        ),
    ]
