# Generated by Django 2.0.5 on 2019-10-09 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0034_auto_20191009_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswers',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaireanswers',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_answers', to='emr.Questionnaire'),
        ),
    ]
