# Generated by Django 2.0.5 on 2019-10-14 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0035_auto_20191009_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies_question_id', models.PositiveIntegerField(blank=True, null=True)),
                ('medication_question_id', models.PositiveIntegerField(blank=True, null=True)),
                ('skincare_medication_question_id', models.PositiveIntegerField(blank=True, null=True)),
                ('prescription_skincare_topicals_id', models.PositiveIntegerField(blank=True, null=True)),
                ('skin_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('hear_about_dearbrightly_id', models.PositiveIntegerField(blank=True, null=True)),
                ('skincare_concerns_id', models.PositiveIntegerField(blank=True, null=True)),
                ('pregnant_or_nursing_id', models.PositiveIntegerField(blank=True, null=True)),
                ('skincare_topicals_id', models.PositiveIntegerField(blank=True, null=True)),
                ('medical_conditions_id', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_info_for_doctor_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_ids', to='emr.QuestionIds'),
        ),
    ]
