# Generated by Django 2.0.5 on 2019-10-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0036_auto_20191014_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='last_modified_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
