# Generated by Django 2.0.5 on 2019-10-28 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0037_auto_20191023_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Medical Admin Attention', 'medical admin attention'), ('Medical Provider Attention', 'medical provider attention'), ('Require Prescription Update', 'require prescription update'), ('Require Patient Photos Update', 'require patient photos update'), ('Patient Photos Updated', 'patient photos updated'), ('Patient Message', 'patient message')], default='Medical Admin Attention', max_length=32, verbose_name='Flag Type')),
                ('body', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flags', to='emr.Visit')),
            ],
        ),
    ]
