# Generated by Django 2.0.5 on 2019-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0039_auto_20191028_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprescription',
            name='status',
            field=models.CharField(choices=[('Initiated', 'initiated'), ('eRxSent', 'erx sent'), ('Deleted', 'deleted'), ('Error', 'error'), ('Edited', 'edited'), ('Disable', 'disable')], default='Initiated', max_length=32, verbose_name='Patient prescription status'),
        ),
    ]
