# Generated by Django 2.0.5 on 2019-12-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0040_auto_20191115_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='last_modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
