# Generated by Django 2.0.5 on 2019-12-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_medicalprovideruser'),
        ('emr', '0041_auto_20191229_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='medical_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_provider_notes', to='users.MedicalProviderUser'),
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='medical_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_provider_prescriptions', to='users.MedicalProviderUser'),
        ),
        migrations.AddField(
            model_name='visit',
            name='medical_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_provider_visits', to='users.MedicalProviderUser'),
        ),
    ]
