# Generated by Django 2.0.5 on 2019-12-30 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0042_auto_20191229_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprescription',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
