# Generated by Django 2.0.5 on 2020-03-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0045_questionids_gender_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit'), ('Short Repeat Visit Female', 'short repeat visit female'), ('Short Repeat Visit Male', 'short repeat visit male')], max_length=32),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service',
            field=models.CharField(choices=[('Initial Visit', 'initial visit'), ('Repeat Visit', 'repeat visit'), ('Short Repeat Visit Female', 'short repeat visit female'), ('Short Repeat Visit Male', 'short repeat visit male')], default='Initial Visit', max_length=32),
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='additional_info_for_doctor_id',
            new_name='additional_info_for_doctor_question_id',
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='hear_about_dearbrightly_id',
            new_name='how_did_you_hear_about_us_question_id',
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='medical_conditions_id',
            new_name='medical_conditions_question_id',
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='pregnant_or_nursing_id',
            new_name='pregnant_or_nursing_question_id',
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='prescription_skincare_topicals_id',
            new_name='prescription_skincare_topicals_question_id',
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='skin_type_id',
            new_name='skin_type_question_id',
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='skincare_concerns_id',
            new_name='skincare_concerns_question_id',
        ),
        migrations.RenameField(
            model_name='questionids',
            old_name='skincare_topicals_id',
            new_name='skincare_topicals_question_id',
        ),
    ]
