# Generated by Django 2.0.5 on 2020-03-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0047_auto_20200317_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionids',
            name='changes_to_skin_question_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
