# Generated by Django 2.0.5 on 2020-03-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0051_update_skin_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('Front of face', 'front face'), ('Right side of face', 'right face'), ('Left side of face', 'left face'), ('Photo ID', 'photo id')], default='Front of face', max_length=32, verbose_name='Photo type'),
        ),
    ]
