# Generated by Django 2.0.5 on 2020-10-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0052_auto_20200327_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprescription',
            name='status',
            field=models.CharField(choices=[('Initiated', 'initiated'), ('eRxSent', 'erx sent'), ('Deleted', 'deleted'), ('Error', 'error'), ('Edited', 'edited'), ('Disable', 'disable'), ('PharmacyVerified', 'pharmacy verified')], default='Initiated', max_length=32, verbose_name='Patient prescription status'),
        ),
    ]
