# Generated by Django 2.0.5 on 2021-01-01 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0054_auto_20201029_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='provider',
        ),
    ]
