# Generated by Django 2.0.5 on 2021-01-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0055_remove_visit_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprescription',
            name='provider',
        ),
    ]
