# Generated by Django 2.0.5 on 2021-06-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0057_visit_rx_prescribed_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='payment_processor_transfer_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Strpie Transfer ID'),
        ),
    ]
