# Generated by Django 2.0.5 on 2021-06-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0058_visit_payment_processor_transfer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionids',
            name='influencer_question_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
