# Generated by Django 2.0.5 on 2021-07-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0059_questionids_influencer_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='payment_processor_transfer_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Stripe Transfer ID'),
        ),
    ]
