# Generated by Django 2.0.5 on 2021-07-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0060_auto_20210702_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='notes',
            field=models.CharField(blank=True, max_length=128, verbose_name='Admin notes'),
        ),
    ]
