# Generated by Django 2.0.5 on 2021-07-24 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0061_visit_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='medical_provider',
        ),
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
