# Generated by Django 2.0.5 on 2023-01-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0064_featureflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureFlag',
        ),
    ]
