# Generated by Django 2.0.5 on 2023-04-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0065_delete_featureflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='category',
            field=models.CharField(choices=[('Medical Admin Attention', 'medical admin attention'), ('Medical Provider Attention', 'medical provider attention'), ('Require Prescription Update', 'require prescription update'), ('Require Patient Photos Update', 'require patient photos update'), ('Patient Photos Updated', 'patient photos updated'), ('Require Medical Admin Update', 'require medical admin update'), ('Patient Message', 'patient message')], default='Medical Admin Attention', max_length=32, verbose_name='Flag Category'),
        ),
    ]
