# Generated by Django 2.0.5 on 2018-08-24 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20180823_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('payment_processor', models.CharField(choices=[('Stripe', 'stripe'), ('Braintree', 'braintree'), ('Square', 'square')], default='Stripe', max_length=16, verbose_name='Payment Processor')),
                ('payment_processor_customer_id', models.CharField(blank=True, max_length=255, verbose_name='Payment Processor Customer ID')),
                ('payment_processor_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='Payment Processor Transaction ID')),
                ('total', models.IntegerField(default=0, verbose_name='The total amount that the user paid')),
                ('tax', models.IntegerField(default=0, verbose_name='Tax amount')),
                ('shipping_fee', models.IntegerField(default=0, verbose_name='Shipping fee')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount amount')),
                ('discount_code', models.CharField(blank=True, max_length=20, verbose_name='Discount code')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Awaiting Payment', 'awaiting payment'), ('Awaiting Fulfillment', 'awaiting fulfillment'), ('Awaiting User Input', 'awaiting user input'), ('Awaiting Shipment', 'awaiting shipment'), ('Awaiting Pickup', 'awaiting pickup'), ('Partially Shipped', 'partially shipped'), ('Completed', 'completed'), ('Shipped', 'shipped'), ('Cancelled', 'cancelled'), ('Declined', 'declined'), ('Refunded', 'refunded'), ('Disputed', 'disputed'), ('Manual Verification Required', 'manual verification required'), ('Partially Refunded', 'partially refunded')], default='Pending', max_length=32, verbose_name='Order status')),
                ('notes', models.CharField(blank=True, max_length=512, verbose_name='Admin notes')),
                ('order_type', models.CharField(choices=[('Refill', 'refill'), ('Rx', 'rx'), ('OTC', 'otc'), ('Rx/OTC', 'rx otc')], default='Refill', max_length=255, verbose_name='Type of the order')),
                ('is_archived', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('subscription_frequency', models.CharField(choices=[('Once', 'once'), ('Every 3 months', 'every three months')], default='Once', max_length=255, verbose_name='Subscriptionfrequency in months')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity of products made in the order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_to_order', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='products_set', to='orders.OrderProduct'),
        ),
    ]
