# Generated by Django 2.0.5 on 2018-08-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180824_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='subscription_frequency',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='frequency',
            field=models.CharField(choices=[('Once', 'once'), ('Every 3 months', 'every three months')], default='Once', max_length=255, null=True, verbose_name='Subscription frequency in months'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.Product'),
        ),
    ]
