# Generated by Django 2.0.5 on 2018-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180824_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_processor_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='medical_visit_id',
            field=models.IntegerField(default=0, verbose_name='Visit ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_processor_charge_id',
            field=models.CharField(blank=True, max_length=256, verbose_name='Payment Processor Charge ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_processor_order_id',
            field=models.CharField(blank=True, max_length=256, verbose_name='Payment Processor Order ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.IntegerField(default=0, verbose_name='The sub total amount that the user paid'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='payment_processor_subscription_id',
            field=models.CharField(blank=True, max_length=256, verbose_name='Payment Processor Subscription ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_processor_customer_id',
            field=models.CharField(blank=True, max_length=256, verbose_name='Payment Processor Customer ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Checkout Initiated', 'checkout initiated'), ('Checkout Shipping Address Completed', 'checkout shipping address complete'), ('Checkout Payment Authorized', 'checkout payment authorized'), ('Checkout Payment Captured', 'checkout payment captured'), ('Checkout Payment Declined', 'checkout payment declined'), ('Medical Visit Eligibility Verified', 'medical visit eligibility verified'), ('Medical Visit Ineligible', 'medical visit ineligible'), ('Medical Visit Terms Accepted', 'medical visit terms accepted'), ('Medical Visit Questionnaire Completed', 'medical visit questionnaire completed'), ('Medical Visit Photos Uploaded', 'medical visit photos uploaded'), ('Medical Visit Provider Pending', 'medical visit provider pending'), ('Medical Visit Provider Awaiting User Input', 'medical visit provider awaiting user input'), ('Medical Visit Provider Rx Submitted', 'medical visit provider rx submitted'), ('Medical Visit Provider Rx Denied', 'medical visit provider rx denied'), ('Medical Visit Provider Cancelled', 'medical visit provider cancelled'), ('Pharmacy Rx Received', 'pharmacy rx received'), ('Pharmacy Rx Fulfilled', 'pharmacy rx fulfilled'), ('Pharmacy Rx Shipped', 'pharmacy rx shipped'), ('Pharmacy Rx Error', 'pharmacy rx error'), ('Shipped', 'shipped'), ('Picked Up', 'picked up'), ('Cancelled', 'cancelled'), ('Refunded', 'refunded'), ('Disputed', 'disputed'), ('Manual Verification Required', 'manual verification required')], default='Pending', max_length=32, verbose_name='Order status'),
        ),
    ]
