# Generated by Django 2.0.5 on 2018-08-27 13:43

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180825_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
    ]
