# Generated by Django 2.0.5 on 2018-08-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_uuid'),
        ('orders', '0008_auto_20180827_1626'),
    ]

    operations = [
    ]
