# Generated by Django 2.0.5 on 2018-08-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180827_1343'),
        ('orders', '0009_merge_20180828_0756'),
    ]

    operations = [
    ]
