# Generated by Django 2.0.5 on 2018-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20180828_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Refill', 'refill'), ('Rx', 'rx'), ('OTC', 'otc'), ('Rx/OTC', 'rx otc')], default='Refill', max_length=255, verbose_name='Type of the order'),
        ),
    ]
