# Generated by Django 2.0.5 on 2018-08-31 08:11

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import rest_framework.compat


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180831_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percent',
            field=models.PositiveIntegerField(default=10, validators=[rest_framework.compat.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=10),
        ),
    ]
