# Generated by Django 2.0.5 on 2018-09-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180831_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='grand_total_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_total_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_percent',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
