# Generated by Django 2.0.5 on 2018-09-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='shipping_details',
        ),
    ]
