# Generated by Django 2.0.5 on 2018-09-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180910_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medical_visit_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Refill', 'refill'), ('Rx', 'rx'), ('OTC', 'otc')], default='Refill', max_length=255, verbose_name='Type of the order'),
        ),
    ]
