# Generated by Django 2.0.5 on 2018-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180927_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_refill',
            field=models.BooleanField(default=False),
        ),
    ]
