# Generated by Django 2.0.5 on 2018-10-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_orderproduct_is_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount amount for product'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price of all items of this product.'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tax_rate',
            field=models.FloatField(default=0, verbose_name='Tax rate for product'),
        ),
    ]
