# Generated by Django 2.0.5 on 2018-10-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20181005_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Discount amount for product'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='tax_rate',
            field=models.FloatField(default=0, null=True, verbose_name='Tax rate for product'),
        ),
    ]
