# Generated by Django 2.0.5 on 2018-10-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_order_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.PositiveIntegerField(default=0, verbose_name='This is the final total the user will be charged for.'),
        ),
    ]
