# Generated by Django 2.0.5 on 2018-10-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
    ]
