# Generated by Django 2.0.5 on 2018-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20181012_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Refill', 'refill'), ('Rx', 'rx'), ('OTC', 'otc')], default='Rx', max_length=255, verbose_name='Type of the order'),
        ),
    ]
