# Generated by Django 2.0.5 on 2018-10-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20181012_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Checkout Initiated'), (2, 'Checkout Shipping Address Completed'), (3, 'Checkout Payment Authorized'), (4, 'Checkout Payment Captured'), (5, 'Checkout Payment Partially Captured'), (6, 'Checkout Payment Declined'), (7, 'Checkout Payment Refunded')], default=0, max_length=32, verbose_name='Checkout status'),
        ),
        migrations.AddField(
            model_name='order',
            name='medical_visit_status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Eligibility Verified'), (2, 'Ineligible'), (3, 'Terms Accepted'), (4, 'Questionnaire Completed'), (5, 'Photos Uploaded'), (6, 'Provider Pending'), (7, 'Provider Awaiting User Input'), (8, 'Provider Rx Submitted'), (9, 'Provider Rx Denied'), (10, 'Provider Cancelled')], default=0, max_length=32, verbose_name='Medical visit status'),
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy_status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Pharmacy Rx Received'), (2, 'Pharmacy Rx Fulfilled'), (3, 'Pharmacy Rx Shipped'), (4, 'Pharmacy Rx Error')], default=0, max_length=32, verbose_name='Pharmacy status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='medical_visit_fee',
            field=models.PositiveIntegerField(default=30000),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Awaiting Fulfillment'), (2, 'Shipped'), (3, 'Picked Up'), (4, 'Cancelled'), (5, 'Returned'), (6, 'Partially Returned'), (7, 'Disputed'), (8, 'Manual Verification Required')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
