# Generated by Django 2.0.5 on 2018-10-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20181012_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (2, 'Awaiting Fulfillment'), (2, 'Awaiting Shipment'), (3, 'Shipped'), (4, 'Picked Up'), (5, 'Cancelled'), (6, 'Returned'), (8, 'Partially Returned'), (9, 'Disputed'), (10, 'Manual Verification Required')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
