# Generated by Django 2.0.5 on 2018-10-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20181012_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Rx', 'rx'), ('OTC', 'otc')], default='Rx', max_length=255, verbose_name='Type of the order'),
        ),
    ]
