# Generated by Django 2.0.5 on 2018-10-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20181012_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medical_visit_status',
        ),
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='medical_visit_fee',
            field=models.PositiveIntegerField(default=3000),
        ),
    ]
