# Generated by Django 2.0.5 on 2018-10-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20181013_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
