# Generated by Django 2.0.5 on 2018-10-16 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20181014_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medical_visit_id',
        ),
    ]
