# Generated by Django 2.0.5 on 2018-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20181016_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='questionnaire_type',
            field=models.CharField(choices=[('None', 'none'), ('New User', 'new user'), ('Returning User', 'returning user')], default='None', max_length=32, verbose_name='Type of the questionnaire'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Rx', 'rx'), ('OTC', 'otc')], default='Rx', max_length=32, verbose_name='Type of the order'),
        ),
    ]
