# Generated by Django 2.0.5 on 2018-10-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20181021_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
    ]
