# Generated by Django 2.0.5 on 2018-10-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_remove_order_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
    ]
