# Generated by Django 2.0.5 on 2018-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_remove_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Checkout Initiated'), (2, 'Checkout Shipping Address Completed'), (3, 'Checkout Visit Complete'), (4, 'Checkout Payment Authorized'), (5, 'Checkout Payment Captured'), (6, 'Checkout Payment Partially Captured'), (7, 'Checkout Payment Declined'), (8, 'Checkout Payment Refunded')], default=0, max_length=32, verbose_name='Checkout status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Awaiting Fulfillment'), (2, 'Awaiting Shipment'), (3, 'Shipped'), (4, 'Picked Up'), (5, 'Cancelled'), (6, 'Returned'), (7, 'Partially Returned'), (8, 'Disputed'), (9, 'Manual Verification Required')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
