# Generated by Django 2.0.5 on 2018-10-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20181023_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_refill',
        ),
    ]
