# Generated by Django 2.0.5 on 2018-10-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_remove_order_questionnaire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='medical_visit_fee',
            field=models.PositiveIntegerField(default=2900),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.PositiveIntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.ShippingDetails'),
        ),
    ]
