# Generated by Django 2.0.5 on 2018-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20181026_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Account Created'), (1, 'Pending Questionnaire'), (2, 'Pending Medical Provider Review'), (3, 'Pending Pharmacy'), (4, 'Awaiting Fulfillment'), (5, 'Shipped'), (6, 'Refill Submitted'), (7, 'Refunded'), (8, 'Cancelled'), (9, 'Manual Verification Required')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
