# Generated by Django 2.0.5 on 2018-11-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_status',
            field=models.CharField(choices=[(0, 'Initiated'), (1, 'Shipping Address Completed'), (2, 'Payment Authorized'), (3, 'Questionnaire Complete'), (4, 'Photos Uploaded'), (5, 'Payment Captured'), (6, 'Payment Partially Captured'), (7, 'Payment Declined')], default=0, max_length=32, verbose_name='Checkout status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_processor',
            field=models.CharField(choices=[(0, 'Stripe'), (1, 'Braintree'), (2, 'Square'), (3, 'PayPal')], default=0, max_length=16, verbose_name='Payment Processor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Account Created'), (1, 'Pending Questionnaire'), (2, 'Pending Photos'), (3, 'Pending Medical Provider Review'), (4, 'Pending Pharmacy'), (5, 'Awaiting Fulfillment'), (6, 'Shipped'), (7, 'Refill Submitted'), (8, 'Refunded'), (9, 'Cancelled'), (10, 'Manual Verification Required')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
