# Generated by Django 2.0.5 on 2018-12-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20181212_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_status',
            field=models.CharField(choices=[(0, 'Initiated'), (1, 'Shipping Address Completed'), (2, 'Payment Authorized'), (3, 'Questionnaire Complete'), (4, 'Photos Uploaded'), (5, 'Payment Captured'), (6, 'Payment Partially Captured'), (7, 'Payment Declined'), (8, 'Confirmation Email Sent')], default=0, max_length=32, verbose_name='Checkout status'),
        ),
    ]
