# Generated by Django 2.0.5 on 2018-12-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_auto_20181217_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchased_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
