# Generated by Django 2.0.5 on 2018-12-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_order_purchased_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
