# Generated by Django 2.0.5 on 2018-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_auto_20181220_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
