# Generated by Django 2.0.5 on 2018-12-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Price of all items of this product.'),
        ),
    ]
