# Generated by Django 2.0.5 on 2019-01-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='medical_visit_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
