# Generated by Django 2.0.5 on 2019-01-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_auto_20190104_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchased_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
