# Generated by Django 2.0.5 on 2019-03-07 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_auto_20190122_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='autogenerated',
            field=models.BooleanField(default=False, verbose_name='Autogenerated for subscription orders'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_captured_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_status',
            field=models.CharField(choices=[(0, 'Initiated'), (1, 'Shipping Address Completed'), (2, 'Payment Authorized'), (3, 'Questionnaire Complete'), (4, 'Photos Uploaded'), (5, 'Payment Captured'), (6, 'Payment Partially Captured'), (7, 'Payment Declined'), (8, 'Confirmation Email Sent'), (9, 'Subscription Order Autogenerated'), (10, 'Upcoming Subscription Order Email Sent'), (11, 'Subscription Order Payment Captured'), (12, 'Subscription Order Payment Failed'), (12, 'Subscription Paused for this Order')], default=0, max_length=32, verbose_name='Checkout status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Account Created'), (1, 'Pending Questionnaire'), (2, 'Pending Photos'), (3, 'Pending Medical Provider Review'), (4, 'Pending Pharmacy'), (5, 'Awaiting Fulfillment'), (6, 'Shipped'), (7, 'Refill Submitted'), (8, 'Refunded'), (9, 'Cancelled'), (10, 'Manual Verification Required'), (11, 'Subscription Order Autogenerated')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
