# Generated by Django 2.0.5 on 2019-03-07 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190304_2313'),
        ('products', '0023_auto_20190218_0930'),
        ('orders', '0059_order_subscriptions_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_product_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='subscriptions.OrderProductSubscription'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='subscription_current_period_start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity of products made in the order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='payment_processor_subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True,
                                   verbose_name='Payment Processor Subscription ID'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='tax_rate',
            field=models.FloatField(default=0, null=True, verbose_name='Tax rate for item'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Discount amount for item'),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='is_refill',
        ),
    ]
