# Generated by Django 2.0.5 on 2019-03-07 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190304_2313'),
        ('products', '0023_auto_20190218_0930'),
        ('orders', '0060_order_products_subscriptions_add_alter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('discount', models.PositiveIntegerField(default=0, null=True, verbose_name='Discount amount for item')),
                ('is_refill', models.BooleanField(default=False)),
                ('payment_processor_subscription_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Payment Processor Subscription ID')),
                ('is_invoice_created', models.BooleanField(default=False)),
                ('is_charged', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=0, null=True, verbose_name='Price of item, not including discounts, shipping, or tax.')),
                ('tax', models.PositiveIntegerField(default=0, null=True, verbose_name='Tax amount for item')),
                ('tax_rate', models.FloatField(default=0, null=True, verbose_name='Tax rate for item')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_item_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='subscriptions.OrderItemSubscription'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.OrderProduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.Product'),
        ),
    ]
