# Generated by Django 2.0.5 on 2019-04-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_create_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tracking number'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tracking URL'),
        ),
    ]
