# Generated by Django 2.0.5 on 2019-04-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_auto_20190404_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
