# Generated by Django 2.0.5 on 2019-04-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_order_seen_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_subscription',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_product_subscription',
        ),
    ]
