# Generated by Django 2.0.5 on 2019-04-22 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_auto_20190420_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_processor_customer_id',
        ),
    ]
