# Generated by Django 2.0.5 on 2019-04-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0067_remove_order_payment_processor_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment_processor_subscription_id',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='tax_rate',
        ),
    ]
