# Generated by Django 2.0.5 on 2019-04-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_auto_20190425_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_processor_order_id',
        ),
    ]
