# Generated by Django 2.0.5 on 2019-05-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0069_remove_order_payment_processor_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_processor_invoice_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Payment Processor Invoice ID'),
        ),
    ]
