# Generated by Django 2.0.5 on 2019-05-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_order_payment_processor_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='Delay of subscription order in months'),
        ),
    ]
