# Generated by Django 2.0.5 on 2019-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_order_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chart_mogul_invoice_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Chart Mogul Invoice ID'),
        ),
    ]
