# Generated by Django 2.0.5 on 2019-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_order_chart_mogul_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='chart_mogul_invoice_id',
        ),
        migrations.AddField(
            model_name='order',
            name='chart_mogul_invoice_uuid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Chart Mogul Invoice UUID'),
        ),
    ]
