# Generated by Django 2.0.5 on 2019-06-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0073_auto_20190524_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_processor_invoice_id',
        ),
    ]
