# Generated by Django 2.0.5 on 2019-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_remove_order_payment_processor_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delay_in_days',
            field=models.IntegerField(default=0, verbose_name='Delay of subscription in days'),
        ),
    ]
