# Generated by Django 2.0.5 on 2019-06-29 06:15

from django.db import migrations, models

def update_order_payment_checkout_type(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(payment_captured_datetime__isnull=False):
        order.payment_checkout_type = 1 #Order.PaymentCheckoutType.credit_card
        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0075_order_delay_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_checkout_type',
            field=models.CharField(choices=[(0, 'None'), (1, 'Credit Card'), (3, 'Apple Pay'), (4, 'Google Pay')],
                                   default=0, max_length=1, verbose_name='Payment checkout type'),
        ),
        migrations.RunPython(update_order_payment_checkout_type),
    ]