# Generated by Django 2.0.5 on 2019-07-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0076_order_payment_checkout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_checkout_type',
            field=models.CharField(choices=[(0, 'None'), (1, 'Credit Card'), (2, 'Apple Pay'), (3, 'Google Pay')], default=0, max_length=1, verbose_name='Payment checkout type'),
        ),
    ]
