# Generated by Django 2.0.5 on 2019-07-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0078_auto_20190703_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_trial',
            field=models.BooleanField(default=False, verbose_name='Trial order for first-time customers'),
        ),
    ]
