# Generated by Django 2.0.5 on 2019-07-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_auto_20190716_2120'),
        ('orders', '0079_order_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emr_medical_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='emr.Visit'),
        ),
    ]
