# Generated by Django 2.0.5 on 2019-08-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_auto_20190721_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_status',
            field=models.CharField(choices=[(0, 'Initiated'), (1, 'Shipping Address Completed'), (2, 'Payment Authorized'), (3, 'Questionnaire Complete'), (4, 'Photos Uploaded'), (5, 'Payment Captured'), (6, 'Payment Partially Captured'), (7, 'Payment Declined'), (8, 'Confirmation Email Sent'), (9, 'Subscription Order Autogenerated'), (10, 'Upcoming Subscription Order Email Sent'), (11, 'Subscription Order Payment Captured'), (12, 'Subscription Order Payment Failed'), (13, 'Subscription Paused for this Order')], default=0, max_length=32, verbose_name='Checkout status'),
        ),
    ]
