# Generated by Django 2.0.5 on 2019-08-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0082_auto_20190808_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delay',
        ),
    ]
