# Generated by Django 2.0.5 on 2019-08-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0083_remove_order_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_url',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Shipping Carrier'),
        ),
    ]
