# Generated by Django 2.0.5 on 2019-11-18 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0088_auto_20191111_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_trial',
        ),
    ]
