# Generated by Django 2.0.5 on 2020-01-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0092_orderproduct_subscription_current_period_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='subscription_current_period_end_datetime',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='subscription_current_period_start_datetime',
        ),
    ]
