# Generated by Django 2.0.5 on 2020-02-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0094_auto_20200204_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delay_in_days',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pharmacy_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_paid',
        ),
    ]
