# Generated by Django 2.0.5 on 2020-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0095_auto_20200205_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_klaviyo_migrated',
            field=models.BooleanField(default=False, verbose_name='Migrated over to Klaviyo'),
        ),
    ]
