# Generated by Django 2.0.5 on 2020-10-20 23:38

from django.db import migrations, models
from django.db.models import Q
from django.conf import settings


def is_rx_order(order):
    rx_items = order.order_items.filter(product__product_type='Rx')
    return len(rx_items) > 0

def update_default_onboarding_flow_type(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        if is_rx_order(order):
            order.onboarding_flow_type = 'control'
            order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0097_auto_20200828_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='onboarding_flow_type',
            field=models.CharField(default='otc', max_length=32, verbose_name='Determines the onboarding flow type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Account Created'), (1, 'Pending Questionnaire'), (2, 'Pending Photos'), (3, 'Pending Medical Provider Review'), (4, 'Pending Pharmacy'), (5, 'Awaiting Fulfillment'), (6, 'Shipped'), (7, 'Pending Payment'), (8, 'Refunded'), (9, 'Cancelled'), (10, 'Manual Verification Required'), (11, 'Subscription Order Autogenerated'), (12, 'Skin Profile Complete'), (13, 'Payment Complete'), (14, 'Payment Override')], default=0, max_length=32, verbose_name='Order status'),
        ),
        migrations.RunPython(update_default_onboarding_flow_type),
    ]