# Generated by Django 2.0.5 on 2021-01-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0098_auto_20201020_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
