# Generated by Django 2.0.5 on 2021-03-12 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20201231_0851'),
        ('orders', '0099_order_delivered_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'product'), ('bottle', 'bottle'), ('mailer', 'mailer')], default='product', max_length=32, verbose_name='Type of Inventory')),
                ('bottle_type', models.CharField(choices=[('none', 'none'), ('refillable bottle', 'refillable bottle'), ('refill', 'refill'), ('non refillable bottle', 'non refillable bottle')], default='non refillable bottle', max_length=32, verbose_name='Inventory Bottle Type')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('starting_order_number', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bottle_type',
            field=models.CharField(choices=[('none', 'none'), ('refillable bottle', 'refillable bottle'), ('refill', 'refill'), ('non refillable bottle', 'non refillable bottle')], default='non refillable bottle', max_length=32, verbose_name='Bottle type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Account Created'), (1, 'Pending Questionnaire'), (2, 'Pending Photos'), (3, 'Pending Medical Provider Review'), (4, 'Pending Pharmacy'), (5, 'Awaiting Fulfillment'), (6, 'Shipped'), (7, 'Pending Payment'), (8, 'Refunded'), (9, 'Cancelled'), (10, 'Manual Verification Required'), (11, 'Subscription Order Autogenerated'), (12, 'Skin Profile Complete'), (13, 'Payment Complete'), (14, 'Payment Override'), (15, 'Returned')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
