# Generated by Django 2.0.5 on 2021-03-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0101_update_trial_order_to_trial_retinoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_remaining_notification',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(choices=[('product', 'product'), ('bottle', 'bottle'), ('packaging', 'packaging'), ('pamphlet', 'pamphlet')], default='product', max_length=32, verbose_name='Type of Inventory'),
        ),
    ]
