# Generated by Django 2.0.5 on 2021-03-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0102_auto_20210318_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='starting_order_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
