# Generated by Django 2.0.5 on 2021-04-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0103_auto_20210319_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='bottle_type',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('refillable bottle', 'refillable bottle'), ('refill', 'refill'), ('non refillable bottle', 'non refillable bottle')], default='non refillable bottle', max_length=32, null=True, verbose_name='Inventory Bottle Type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
