# Generated by Django 2.0.5 on 2021-07-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0107_auto_20210702_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=256, verbose_name='Admin notes'),
        ),
    ]
