# Generated by Django 2.0.5 on 2021-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0108_auto_20210702_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
