# Generated by Django 2.0.5 on 2021-10-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0110_auto_20210924_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Shipping Carrier'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tracking number'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
