# Generated by Django 2.0.5 on 2022-01-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0111_auto_20211027_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='smart_warehouse_submit_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
