# Generated by Django 2.0.5 on 2022-01-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0112_auto_20220121_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Account Created'), (1, 'Pending Questionnaire'), (2, 'Pending Photos'), (3, 'Pending Medical Provider Review'), (4, 'Pending Pharmacy'), (5, 'Awaiting Fulfillment'), (6, 'Shipped'), (7, 'Pending Payment'), (8, 'Refunded'), (9, 'Cancelled'), (10, 'Payment Failure'), (11, 'Subscription Order Autogenerated'), (12, 'Skin Profile Complete'), (13, 'Payment Complete'), (14, 'Payment Override'), (15, 'Returned'), (16, 'Partially Shipped')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
