# Generated by Django 2.0.5 on 2023-01-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0115_remove_duplicate_order_products_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopify_order_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Shopify Order ID'),
        ),
    ]
