# Generated by Django 2.0.5 on 2023-01-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0116_order_shopify_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Discount code'),
        ),
    ]
