# Generated by Django 2.0.5 on 2023-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0117_auto_20230112_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shopify_order_id',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True, verbose_name='Shopify Order ID'),
        ),
    ]
