# Generated by Django 2.0.5 on 2023-06-12 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0034_auto_20230530_0919'),
        ('orders', '0119_auto_20230322_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_processor_subscription_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_processor_card_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Payment Processor Card ID'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='subscriptions.Subscription'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Unit price of item, not including discounts, shipping, or tax.'),
        ),
    ]
