# Generated by Django 2.0.5 on 2018-08-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('rx', 'rx'), ('moisturizer', 'moisturizer'), ('sunblock', 'sunblock'), ('gift card', 'gift card')], default='rx', max_length=32, verbose_name='Type')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='Description')),
                ('quantity_available', models.IntegerField(default=0, verbose_name='Quantity available')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('quantity_unit', models.CharField(blank=True, max_length=16, verbose_name='Quantity unit')),
                ('strength', models.IntegerField(default=0, verbose_name='Strength')),
                ('strength_unit', models.CharField(blank=True, max_length=16, verbose_name='Strength unit')),
                ('vehicle', models.CharField(blank=True, max_length=32, verbose_name='Vehicle')),
                ('days_supply', models.IntegerField(default=0, verbose_name='Days supply')),
                ('sku', models.CharField(blank=True, max_length=32, verbose_name='SKU')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
        ),
    ]
