# Generated by Django 2.0.5 on 2018-08-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180827_1337'),
        ('products', '0005_product_image'),
    ]

    operations = [
    ]
