# Generated by Django 2.0.5 on 2018-09-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180828_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Benefits'),
        ),
        migrations.AddField(
            model_name='product',
            name='grade',
            field=models.CharField(blank=True, max_length=64, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.CharField(blank=True, max_length=1024, verbose_name='How to use'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients_highlight',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Ingredients highlight'),
        ),
    ]
