# Generated by Django 2.0.5 on 2018-09-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180906_1230'),
        ('products', '0009_auto_20180905_1317'),
    ]

    operations = [
    ]
