# Generated by Django 2.0.5 on 2018-09-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Determines if the product is browsable by users.', verbose_name='hidden'),
        ),
    ]
