# Generated by Django 2.0.5 on 2018-09-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grade',
        ),
    ]
