# Generated by Django 2.0.5 on 2018-09-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('rx', 'rx'), ('otc', 'otc'), ('gift card', 'gift card'), ('service', 'service')], default='rx', max_length=32, verbose_name='Type'),
        ),
    ]
