# Generated by Django 2.0.5 on 2018-09-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180928_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('rx', 'rx'), ('otc', 'otc'), ('gift card', 'gift card'), ('service', 'service'), ('shipping', 'shipping')], default='rx', max_length=32, verbose_name='Type'),
        ),
    ]
