# Generated by Django 2.0.5 on 2018-09-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20180928_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_summary',
            field=models.CharField(blank=True, max_length=64, verbose_name='Name'),
        ),
    ]
