# Generated by Django 2.0.5 on 2018-10-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_product_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Rx', 'rx'), ('OTC', 'otc'), ('Gift Card', 'gift card'), ('Service', 'service'), ('Shipping', 'shipping')], default='Rx', max_length=32, verbose_name='Type'),
        ),
    ]
