# Generated by Django 2.0.5 on 2018-10-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181014_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False, help_text='Determines if the product is a collection of other products.', verbose_name='hidden'),
        ),
        migrations.AddField(
            model_name='product',
            name='set_sku',
            field=models.CharField(blank=True, max_length=32, verbose_name='Set SKU'),
        ),
    ]
