# Generated by Django 2.0.5 on 2018-10-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20181023_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False, help_text='Determines if the product is a collection of other products.', verbose_name='is set'),
        ),
    ]
