# Generated by Django 2.0.5 on 2018-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20181023_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
