# Generated by Django 2.0.5 on 2018-12-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_large_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_time_purchase_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
