# Generated by Django 2.0.5 on 2018-12-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_first_time_purchase_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='first_time_purchase_discount',
            new_name='first_time_trial_discount',
        ),
    ]
