# Generated by Django 2.0.5 on 2019-02-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20181222_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('none', 'none'), ('retinoid', 'retinoid'), ('moisturizer', 'moisturizer')], default='none', max_length=64, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='setproduct',
            name='product_in_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets', to='products.Product'),
        ),
        migrations.AddField(
            model_name='setproduct',
            name='set_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_products', to='products.Product'),
        ),
    ]
