# Generated by Django 2.0.5 on 2020-02-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20190218_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_time_trial_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subscription_discount',
        ),
    ]
