# Generated by Django 2.0.5 on 2020-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='refill_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='trial_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
