# Generated by Django 2.0.5 on 2020-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20201215_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=128, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='large_image',
            field=models.CharField(blank=True, max_length=128, verbose_name='Large image'),
        ),
    ]
