# Generated by Django 2.0.5 on 2021-03-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_refill_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='refill_sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='set_sku',
        ),
        migrations.AddField(
            model_name='product',
            name='refill_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
