# Generated by Django 2.0.5 on 2021-04-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20210315_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trial_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_products', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='refill_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refill_products', to='products.Product'),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='refill_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trial_price',
        ),
    ]
