# Generated by Django 2.0.5 on 2021-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210425_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
