# Generated by Django 2.0.5 on 2021-10-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20210904_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='smart_warehouse_sku',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Smart Warehouse SKU'),
        ),
    ]
