# Generated by Django 2.0.5 on 2021-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_smart_warehouse_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='forever_five_reasons',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Forever five'),
        ),
    ]
