# Generated by Django 2.0.5 on 2021-12-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_product_forever_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_plan_product',
            field=models.BooleanField(default=False, help_text='Determines if the product can be added to a plan.', verbose_name='is plan product'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
