# Generated by Django 2.0.5 on 2022-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20211229_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('none', 'none'), ('retinoid', 'retinoid'), ('moisturizer', 'moisturizer'), ('bottle', 'bottle'), ('cleanser', 'cleanser')], default='none', max_length=64, verbose_name='Category'),
        ),
    ]
