# Generated by Django 2.0.5 on 2022-09-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20220308_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='smart_warehouse_sku',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Smart Warehouse SKU'),
        ),
    ]
