# Generated by Django 2.0.5 on 2023-01-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20220910_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bottle_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Bottle type'),
        ),
    ]
