# Generated by Django 2.0.5 on 2019-03-04 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_auto_20190218_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_processor_subscription_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Subscription ID assigned by the payment processor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProductSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('current_period_start_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('frequency', models.IntegerField(default=0, verbose_name='Subscription frequency in months')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this subscription plan is active.', verbose_name='active')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_subscriptions', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='orderitemsubscription',
            name='order_product_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_subscriptions', to='subscriptions.OrderProductSubscription'),
        ),
        migrations.AddField(
            model_name='orderitemsubscription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_subscription_plans', to='products.Product'),
        ),
    ]
