# Generated by Django 2.0.5 on 2019-03-04 23:13

from django.db import migrations, models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsubscription',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemsubscription',
            name='last_modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderproductsubscription',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproductsubscription',
            name='last_modified_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitemsubscription',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='order_item_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitemsubscription',
            name='payment_processor_subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True,
                                   verbose_name='Subscription ID assigned by the payment processor'),
        ),
        migrations.AlterField(
            model_name='orderproductsubscription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='order_product_subscriptions', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='orderproductsubscription',
            name='current_period_start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
