# Generated by Django 2.0.5 on 2019-05-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_create_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductsubscription',
            name='cancel_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderproductsubscription',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='Delay of subscription in months'),
        ),
    ]
