# Generated by Django 2.0.5 on 2019-05-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_auto_20190514_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Name')),
                ('chart_mogul_uuid', models.CharField(blank=True, max_length=128, null=True, verbose_name='Chart Mogul UUID')),
                ('stripe_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Stripe ID')),
                ('interval', models.IntegerField(default=0, verbose_name='Interval in months')),
            ],
        ),
    ]
