# Generated by Django 2.0.5 on 2019-05-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20190218_0930'),
        ('subscriptions', '0005_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='products.Product'),
        ),
    ]
