# Generated by Django 2.0.5 on 2019-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20190524_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductsubscription',
            name='delay_in_days',
            field=models.IntegerField(default=0, verbose_name='Delay of subscription in days'),
        ),
    ]
