# Generated by Django 2.0.5 on 2019-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20190815_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductsubscription',
            name='delay',
        ),
        migrations.AlterField(
            model_name='orderproductsubscription',
            name='cancel_reason',
            field=models.CharField(choices=[('Not Applicable', 'not applicable'), ('None Specified', 'none'), ('Rx Expired', 'rx expired'), ('Pregnant or Nursing', 'pregnant nursing'), ('Using Commercial Retinoid', 'commercial retinoid'), ('Dislike Product', 'dislike product'), ('Ineffective', 'ineffective'), ('Causes Irritation', 'causes irritation'), ('Cost', 'cost'), ('Dislike Subscription', 'dislike subscription'), ('Using Other Skincare Products', 'other skincare products'), ('Payment Failure', 'payment failure')], default='Not Applicable', max_length=32, verbose_name='Cancellation Reason'),
        ),
    ]
