# Generated by Django 2.0.5 on 2020-10-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20191118_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductsubscription',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cancellation Reason'),
        ),
    ]
