# Generated by Django 2.0.5 on 2020-11-06 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0018_auto_20201030_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('delay_in_days', models.IntegerField(default=0, verbose_name='Delay of subscription in days')),
                ('reason', models.CharField(max_length=200, null=True, verbose_name='Reason')),
                ('type', models.CharField(blank=True, choices=[('restart', 'restart'), ('pause', 'pause'), ('cancel', 'cancel'), ('early ship', 'early ship')], max_length=32, verbose_name='Type')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_edits', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_edits', to='subscriptions.OrderProductSubscription')),
            ],
        ),
    ]
