# Generated by Django 2.0.5 on 2020-11-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='frequency_delta',
            field=models.IntegerField(default=0, verbose_name='Frequency delta in days'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='type',
            field=models.CharField(blank=True, choices=[('frequency update', 'frequency update'), ('restart', 'restart'), ('pause', 'pause'), ('cancel', 'cancel'), ('early ship', 'early ship')], max_length=32, verbose_name='Type'),
        ),
    ]
