# Generated by Django 2.0.5 on 2021-02-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_auto_20201110_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='type',
            field=models.CharField(blank=True, choices=[('frequency update', 'frequency update'), ('restart', 'restart'), ('pause', 'pause'), ('cancel', 'cancel'), ('early ship', 'early ship'), ('product update', 'product update')], max_length=32, verbose_name='Type'),
        ),
    ]
