# Generated by Django 2.0.5 on 2021-02-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_auto_20210217_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductsubscription',
            name='discount_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Invoice Subscription ID'),
        ),
        migrations.AddField(
            model_name='orderproductsubscription',
            name='open_invoice_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Unpaid invoice ID'),
        ),
        migrations.AddField(
            model_name='orderproductsubscription',
            name='upcoming_order_email_sent_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
