# Generated by Django 2.0.5 on 2021-07-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_auto_20210423_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='chart_mogul_uuid',
        ),
    ]
