# Generated by Django 2.0.5 on 2021-11-10 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0035_product_smart_warehouse_sku'),
        ('subscriptions', '0024_remove_plan_chart_mogul_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_modified_datetime', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('current_period_start_datetime', models.DateTimeField(null=True)),
                ('current_period_end_datetime', models.DateTimeField(null=True)),
                ('cancel_datetime', models.DateTimeField(null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cancellation Reason')),
                ('frequency', models.IntegerField(default=0, verbose_name='Subscription frequency in months')),
                ('delay_in_days', models.IntegerField(default=0, verbose_name='Delay of subscription in days')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this subscription plan is active.', verbose_name='active')),
                ('discount_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Invoice Subscription ID')),
                ('upcoming_order_email_sent_datetime', models.DateTimeField(null=True)),
                ('open_invoice_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='Unpaid invoice ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='products.Product')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
            ],
        ),
        migrations.RenameField(
            model_name='edit',
            old_name='subscription',
            new_name='subscription_old',
        ),
    ]