# Generated by Django 2.0.5 on 2021-11-10 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_auto_20211110_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='subscription_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_edits', to='subscriptions.Subscription'),
        ),
    ]
