# Generated by Django 2.0.5 on 2022-01-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0027_auto_20211110_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='type',
            field=models.CharField(blank=True, choices=[('frequency update', 'frequency update'), ('restart', 'restart'), ('pause', 'pause'), ('cancel', 'cancel'), ('early ship', 'early ship'), ('product update', 'product update'), ('quantity update', 'quantity update')], max_length=32, verbose_name='Type'),
        ),
    ]
