# Generated by Django 2.0.5 on 2022-10-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0029_remove_duplicate_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='original_frequency',
            field=models.IntegerField(default=0, verbose_name='Original frequency value'),
        ),
        migrations.AddField(
            model_name='edit',
            name='original_quantity',
            field=models.IntegerField(default=0, verbose_name='Original quantity value'),
        ),
        migrations.AddField(
            model_name='edit',
            name='original_ship_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='edit',
            name='updated_frequency',
            field=models.IntegerField(default=0, verbose_name='New frequency value'),
        ),
        migrations.AddField(
            model_name='edit',
            name='updated_quantity',
            field=models.IntegerField(default=0, verbose_name='New quantity value'),
        ),
        migrations.AddField(
            model_name='edit',
            name='updated_ship_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
