# Generated by Django 2.0.5 on 2023-03-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0030_auto_20221017_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='recharge_address_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recharge Subscription Address ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recharge_subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recharge Subscription ID'),
        ),
    ]
