# Generated by Django 2.0.5 on 2023-05-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0031_auto_20230307_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='recharge_payment_method_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recharge Payment Method ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='shipping_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='users.ShippingDetails'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='recharge_subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Recharge Subscription ID'),
        ),
    ]
