# Generated by Django 2.0.5 on 2023-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0032_auto_20230509_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_processor_card_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Payment Processor Card ID'),
        ),
    ]
