# Generated by Django 2.0.5 on 2023-05-30 09:19

from django.db import migrations
from subscriptions.tasks import (
    migrate_existing_shipping_details_and_payment_details 
    as _migrate_existing_shipping_details_and_payment_details
)


def migrate_existing_shipping_details_and_payment_details(apps, schema_editor):
    User = apps.get_model('users', 'User')
    customers_with_existing_subscriptions = User.objects.filter(
        subscriptions__isnull=False,
        shipping_details__isnull=False,
    ).distinct()
    for customer in customers_with_existing_subscriptions:
        _migrate_existing_shipping_details_and_payment_details.delay(customer_id=customer.pk)

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0033_subscription_payment_processor_card_id'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_shipping_details_and_payment_details, reverse_code=migrations.RunPython.noop),
    ]
