# Generated by Django 2.0.5 on 2021-06-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20201013_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='accessed_object_ids',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
