# Generated by Django 2.0.5 on 2020-02-18 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0095_auto_20200205_0640'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_method', models.CharField(choices=[('unknown', 'unknown'), ('fb messenger', 'fb messenger'), ('email', 'email'), ('copy', 'copy text'), ('whatsapp', 'whatsapp'), ('more', 'more')], default='unknown', max_length=32, verbose_name='communication method')),
                ('source', models.CharField(choices=[('unknown', 'unknown'), ('order confirmation', 'order confirmation'), ('navigation bar', 'navigation bar'), ('email', 'email')], default='unknown', max_length=32, verbose_name='source')),
                ('email_type', models.CharField(choices=[('unknown', 'unknown'), ('sign up', 'sign up'), ('empty cart', 'empty cart'), ('abandoned cart', 'abandoned cart'), ('incomplete questionnaire', 'incomplete questionnaire'), ('incomplete photos', 'incomplete photos'), ('incomplete photo id', 'incomplete photo id'), ('order cancelation skin profile expired', 'order cancelation skin profile expired'), ('skin profile completion new user', 'skin profile completion new user'), ('skin profile completion returning user', 'skin profile completion returning user'), ('order shipped trial', 'order shipped trial'), ('order shipped', 'order shipped'), ('order tracking update', 'order tracking update'), ('order arrived', 'order arrived'), ('provider message', 'provider message'), ('user check In', 'user check in'), ('upcoming subscription order rx updated new user', 'upcoming subscription order rx update new user'), ('upcoming subscription order rx unchanged new sser', 'upcoming subscription order rx unchanged new user'), ('upcoming subscription order rx updated returning user', 'upcoming subscription order rx update returning user'), ('upcoming subscription order rx unchanged returning user', 'upcoming subscription order rx unchanged returning user'), ('user annual visit', 'user annual visit'), ('payment failure', 'payment failure'), ('order confirmation ship now', 'order confirmation ship now'), ('order confirmation resume', 'order confirmation resume'), ('order confirmation', 'order confirmation')], default='unknown', max_length=64, verbose_name='email type')),
                ('code', models.CharField(max_length=6, null=True, unique=True, verbose_name='share code')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created datetime')),
                ('modified_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified datetime')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_codes', to='orders.Order')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_share_codes', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_share_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
