# Generated by Django 2.0.5 on 2020-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_remove_sharing_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing',
            name='source',
        ),
        migrations.AddField(
            model_name='sharing',
            name='entry_point',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'order confirmation'), (2, 'navigation bar'), (3, 'email')], default=0, verbose_name='entry_point'),
        ),
    ]
