# Generated by Django 2.0.5 on 2020-04-14 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0009_auto_20200317_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sharings', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referee_sharings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharing',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrer_sharings', to=settings.AUTH_USER_MODEL),
        ),
    ]
