# Generated by Django 2.0.5 on 2021-01-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0013_auto_20201216_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'unknown'), (2, 'sign up'), (3, 'empty cart'), (4, 'abandoned cart'), (5, 'incomplete questionnaire'), (6, 'incomplete photos'), (7, 'incomplete photo id'), (8, 'order cancellation skin profile expired'), (9, 'skin profile completion new user'), (10, 'skin profile completion returning user'), (11, 'order shipped trial'), (12, 'order shipped'), (13, 'order tracking update'), (14, 'order arrived'), (15, 'provider message'), (16, 'user check in'), (17, 'upcoming subscription order rx updated new user'), (18, 'upcoming subscription order rx unchanged new sser'), (19, 'upcoming subscription order rx updated returning user'), (20, 'upcoming subscription order rx unchanged returning user'), (21, 'user annual visit'), (22, 'payment failure'), (23, 'order confirmation ship now'), (24, 'order confirmation resume'), (25, 'order confirmation'), (26, 'sharing program'), (27, 'skin profile completion returning user no change'), (28, 'skin profile completion returning user no change no response'), (29, 'skin profile completion returning user incomplete response'), (30, 'terms_of_use_update')], default=0, verbose_name='email type'),
        ),
    ]
