import { DoublyLinkedList } from "src/common/helpers/DoublyLinkedList";

export const FREE_SHIP_ORDER_ITEM_COUNT_THRESHOLD = 2;
export const DEFAULT_SHIP_RATE = 450;
export const MEDICAL_VISIT_FEE = 2000;
export const SUBSCRIPTION_DISCOUNT = 2000;
export const FIRST_TIME_TRIAL_DISCOUNT = 700;
export const FIRST_TIME_TRIAL_DISCOUNT_CODE = 'TWOMONTHTRIAL7';

export const ORDER_STATUSES = {
    'Account Created': 0,
    'Pending Questionnaire': 1,
    'Pending Photos': 2,
    'Pending Medical Provider Review': 3,
    'Pending Pharmacy': 4,
    'Awaiting Fulfillment': 5,
    'Shipped': 6,
    'Pending Payment':7,
    'Refunded': 8,
    'Cancelled': 9,
    'Payment Failure': 10,
    'Subscription Order Autogenerated': 11,
    'Skin Profile Complete': 12,
    'Payment Complete': 13,
    'Payment Override': 14,
    'Returned': 15
}


// control: payment --> questionnaire --> photos --> complete
// 'your plan' --> 'shipping' --> 'payment' --> 'skin profile' --> 'photo_tips' --> 'photos'
export const ONBOARDING_FLOW_CONTROL_PROGRESS_BAR = ['shipping', 'payment', 'skin profile'];
export const ONBOARDING_FLOW_CONTROL = ['sign up', 'shipping', 'payment', 'payment confirmation', 'skin profile', 'photos', 'photo id', 'order confirmation'];
export const ONBOARDING_FLOW_CONTROL_DOUBLY_LINKED_LIST = new DoublyLinkedList(ONBOARDING_FLOW_CONTROL);

export const ONBOARDING_FLOW_OTC_PROGRESS_BAR = ['shipping', 'payment'];
export const ONBOARDING_FLOW_OTC = ['sign up', 'shipping', 'payment', 'payment confirmation', 'order confirmation'];
export const ONBOARDING_FLOW_OTC_DOUBLY_LINKED_LIST = new DoublyLinkedList(ONBOARDING_FLOW_OTC);

// variation 1: questionnaire --> photos --> payment --> complete
// 'your plan' --> 'skin profile' --> 'photo_tips' --> 'photos' --> 'shipping' --> 'payment'
export const ONBOARDING_FLOW_TYPE_1_PROGRESS_BAR = ['skin profile', 'shipping', 'payment'];
export const ONBOARDING_FLOW_TYPE_1 = ['sign up', 'skin profile', 'photos', 'photo id', 'shipping', 'payment', 'payment confirmation', 'order confirmation'];
export const ONBOARDING_FLOW_TYPE_1_DOUBLY_LINKED_LIST = new DoublyLinkedList(ONBOARDING_FLOW_TYPE_1);

// variation 2: questionnaire --> payment --> photos --> complete
// 'your plan' --> 'skin profile' --> 'shipping' --> 'payment' --> 'photo_tips' --> 'photos'
export const ONBOARDING_FLOW_TYPE_2_PROGRESS_BAR = ['skin profile', 'shipping', 'payment', 'photos'];
export const ONBOARDING_FLOW_TYPE_2 = ['sign up', 'skin profile', 'skin profile complete', 'shipping', 'payment', 'payment confirmation', 'photos', 'photo id', 'order confirmation'];
export const ONBOARDING_FLOW_TYPE_2_DOUBLY_LINKED_LIST = new DoublyLinkedList(ONBOARDING_FLOW_TYPE_2);

// skip_payment: questionnaire --> photos --> complete
// 'your plan' --> 'skin profile' --> 'photos'
export const SKIP_PAYMENT_FLOW_PROGRESS_BAR = ['skin profile', 'photos'];
export const SKIP_PAYMENT_FLOW = ['sign up', 'skin profile', 'photos', 'photo id', 'order confirmation'];
export const SKIP_PAYMENT_FLOW_DOUBLY_LINKED_LIST = new DoublyLinkedList(SKIP_PAYMENT_FLOW);