export const data = [
    {
        shippingDetails: {
            first_name: 'Shigemi',
            last_name: 'Pang',
            phone: '123 456 789',
            address_line1: 'Sunset Boulevard 12',
            address_line2: '',
            city: 'California',
            country: 'US',
            state: 'CA',
            zip: '90210',
        },
        id: 1,
        email: 'shigemi.pang@gmail.com',
        orders: 2,
        dateJoined: 'Feb 17th 2017',
    },
    {
        shippingDetails: {
            first_name: 'Yuhan',
            last_name: 'Shen',
            phone: '777 888 999',
            address_line1: 'Sunset Street 34',
            address_line2: '',
            city: 'California',
            country: 'US',
            state: 'CA',
            zip: '90210',
        },
        id: 2,
        email: 'yuhan.shen@gmail.com',
        orders: 1,
        dateJoined: 'Feb 17th 2017',
    },
    {
        shippingDetails: {
            first_name: 'Kelly',
            last_name: 'Simcox',
            phone: '123 456 789',
            address_line1: 'Sunset Boulevard 12',
            address_line2: '',
            city: 'California',
            country: 'US',
            state: 'CA',
            zip: '90210',
        },
        id: 3,
        email: 'kelly@simcox.com',
        orders: 3,
        dateJoined: 'Feb 17th 2017',
    },
];
