# Generated by Django 2.0.5 on 2022-04-05 07:09

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0037_auto_20211229_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('amount_off', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_redemptions', models.PositiveIntegerField()),
                ('start_duration_range', models.DateTimeField(blank=True, null=True)),
                ('end_duration_range', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Expiring', 'expiring'), ('Infinite', 'infinite')], default='Expiring', max_length=32)),
                ('allowed_customers', models.ManyToManyField(blank=True, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('discounted_products', models.ManyToManyField(blank=True, related_name='coupons', to='products.Product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
