# Generated by Django 2.0.5 on 2022-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='first_time_order',
            field=models.BooleanField(default=False),
        ),
    ]
