# Generated by Django 2.0.5 on 2022-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_coupon_first_time_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discounted_products_not_in_existing_plans_or_orders',
            field=models.BooleanField(default=False),
        ),
    ]
