# Generated by Django 2.0.5 on 2022-09-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_coupon_only_existing_purchasers'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='only_existing_purchasers',
            field=models.BooleanField(default=False),
        ),
    ]
