# Generated by Django 2.0.5 on 2018-08-22 12:14

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=128, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=128, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('postal_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('country', django_countries.fields.CountryField(default='US', max_length=2)),
                ('phone', localflavor.us.models.PhoneNumberField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='users.Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='users.Address'),
        ),
    ]
