# Generated by Django 2.0.5 on 2018-08-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180823_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='ShippingDetails',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='shipping_details',
            new_name='shipping_details',
        ),
    ]
