# Generated by Django 2.0.5 on 2018-08-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180823_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='big_commerce_user_address_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='big_commerce_user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='questionnaire_status',
        ),
    ]
