# Generated by Django 2.0.5 on 2018-09-10 08:48

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    replaces = [('users', '0011_auto_20180907_0845'), ('users', '0012_auto_20180910_0756')]

    dependencies = [
        ('users', '0010_auto_20180828_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('postal_code', localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, default='US', max_length=2)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_details',
        ),
        migrations.DeleteModel(
            name='ShippingDetails',
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.ShippingAddress'),
        ),
    ]