# Generated by Django 2.0.5 on 2018-09-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180910_2004'),
        ('users', '0011_auto_20180907_0845_squashed_0012_auto_20180910_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ShippingDetails',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='shipping_address',
            new_name='shipping_details',
        ),
    ]
