# Generated by Django 2.0.5 on 2018-09-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180910_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='company name'),
        ),
    ]
