# Generated by Django 2.0.5 on 2018-10-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20181005_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shipping_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.ShippingDetails'),
        ),
    ]
