# Generated by Django 2.0.5 on 2019-01-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_payment_processor_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Facebook User Id'),
        ),
    ]
