# Generated by Django 2.0.5 on 2019-01-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_facebook_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sappira_user_password',
            field=models.BinaryField(blank=True, max_length=256, null=True, verbose_name='Sappira user password encrypted base64 encoded'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
