# Generated by Django 2.0.5 on 2019-01-31 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190125_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='company',
        ),
    ]
