# Generated by Django 2.0.5 on 2019-04-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_shippingdetails_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Facebook User ID'),
        ),
    ]
