# Generated by Django 2.0.5 on 2019-05-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20190430_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chart_mogul_user_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Chart Mogul User ID'),
        ),
    ]
