# Generated by Django 2.0.5 on 2019-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_chart_mogul_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chart_mogul_user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='chart_mogul_user_uuid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Chart Mogul User UUID'),
        ),
    ]
