# Generated by Django 2.0.5 on 2019-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_trial_period',
            field=models.BooleanField(default=False, help_text='Tracks if this person is still on the trial period bottle.', verbose_name='trial period status'),
        ),
    ]
