# Generated by Django 2.0.5 on 2019-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_on_trial_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dosespot_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
