# Generated by Django 2.0.5 on 2019-09-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_dosespot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='on_trial_period',
            field=models.BooleanField(default=True, help_text='Tracks if this person is still on the trial period bottle.', verbose_name='trial period status'),
        ),
    ]
