# Generated by Django 2.0.5 on 2019-11-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190924_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_trial_period',
        ),
    ]
