# Generated by Django 2.0.5 on 2019-12-29 09:38

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_user_on_trial_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProviderUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stripe_connect_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Stripe Connect ID')),
                ('medical_visit_fee', models.PositiveIntegerField(default=0, null=True, verbose_name='Medical Visit Fee')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]

