# Generated by Django 2.0.5 on 2020-01-23 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_medicalprovider_update_for_visit_note_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprovideruser',
            name='states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=[], size=None),
        ),
    ]
