# Generated by Django 2.0.5 on 2020-01-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_medicalprovideruser_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_out_marketing_emails',
            field=models.BooleanField(default=False, help_text='Opts out users from any marketing emails', verbose_name='Marketing emails opt out'),
        ),
    ]
