# Generated by Django 2.0.5 on 2020-02-03 19:32

import dearbrightly.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_opt_out_marketing_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprovideruser',
            name='profile_photo_file',
            field=models.FileField(null=True, storage=dearbrightly.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
