# Generated by Django 2.0.5 on 2020-02-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_medicalprovideruser_profile_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprovideruser',
            name='medical_visit_fee',
        ),
        migrations.AddField(
            model_name='medicalprovideruser',
            name='platform_service_fee',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Platform Service Fee'),
        ),
    ]
