# Generated by Django 2.0.5 on 2020-03-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_user_sappira_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sharing_code',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='share code'),
        ),
    ]
