# Generated by Django 2.0.5 on 2020-06-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_sharing_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprovideruser',
            name='profile_photo_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profile Photo File URL'),
        ),
    ]
