# Generated by Django 2.0.5 on 2020-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20200604_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_klaviyo_migrated',
            field=models.BooleanField(default=False, verbose_name='Migrated over to Klaviyo'),
        ),
    ]
