# Generated by Django 2.0.5 on 2020-12-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_user_is_klaviyo_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_required',
            field=models.BooleanField(default=False, verbose_name='Whether the user authentication requires OTP'),
        ),
    ]
