# Generated by Django 2.0.5 on 2021-01-14 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_userotpsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotpsettings',
            name='id',
        ),
        migrations.AlterField(
            model_name='userotpsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
