# Generated by Django 2.0.5 on 2021-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210114_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpsettings',
            name='session_expire_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
