# Generated by Django 2.0.5 on 2021-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_userotpsettings_session_expire_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpsettings',
            name='session_initial_sign_in',
            field=models.BooleanField(default=False),
        ),
    ]
