# Generated by Django 2.0.5 on 2021-01-24 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_userotpsettings_session_initial_sign_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_required',
            field=models.BooleanField(default=False, verbose_name='User authentication requires a OTP'),
        ),
        migrations.AlterField(
            model_name='userotpsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otp_settings', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
