# Generated by Django 2.0.5 on 2021-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20210124_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_required',
        ),
        migrations.RemoveField(
            model_name='userotpsettings',
            name='session_initial_sign_in',
        ),
        migrations.AddField(
            model_name='userotpsettings',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='User enabled 2FA authentication'),
        ),
    ]
