# Generated by Django 2.0.5 on 2022-10-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_user_chart_mogul_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_sending_user_info_to_advertisers',
            field=models.BooleanField(default=True, verbose_name='Allow sending hashed user info to third-party advertisers per our updated Privacy Policy'),
        ),
    ]
