# Generated by Django 2.0.5 on 2023-01-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20221027_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopify_user_id',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Shopify User ID'),
        ),
    ]
