# Generated by Django 2.0.5 on 2022-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20221027_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_in_sms_app_notifications',
            field=models.BooleanField(default=False, verbose_name='App event notifications opt-in'),
        ),
    ]
