# Generated by Django 2.0.5 on 2023-01-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_user_shopify_user_id'),
        ('users', '0052_user_opt_in_sms_app_notifications'),
    ]

    operations = [
    ]
