# Generated by Django 2.0.5 on 2023-01-18 13:38

from django.db import migrations
from utils.logger_utils import logger
import datetime

def update_users_shipping_details(apps, schema_editor):
    User = apps.get_model("users", "User")
    ShippingDetails = apps.get_model("users", "ShippingDetails")
    Order = apps.get_model("orders", "Order")
    users = User.objects.filter(
        shipping_details__isnull=True,
        date_joined__date__gt=datetime.date(2023, 1, 1),
    )
    for user in users:
        try:
            latest_order = user.orders.latest("created_datetime")
        except Order.DoesNotExist:
            logger.debug(
                f"[Migration][update_users_shipping_details] " 
                f"No latest order found for user: {user.id} "
            )
        else:
            if latest_order.shipping_details:
                user_shipping_details = ShippingDetails.objects.create(
                    first_name=latest_order.shipping_details.first_name,
                    last_name=latest_order.shipping_details.last_name,
                    address_line1=latest_order.shipping_details.address_line1,
                    address_line2=latest_order.shipping_details.address_line2,
                    city=latest_order.shipping_details.city,
                    postal_code=latest_order.shipping_details.postal_code,
                    phone=latest_order.shipping_details.phone,
                    country=latest_order.shipping_details.country
                )

                user.shipping_details = user_shipping_details
                user.save()
                logger.debug(
                    f"[Migration][update_users_shipping_details] " 
                    f"Shipping_details updated for user: {user.id}. "
                    f"latest_order.shipping_details: {latest_order.shipping_details.__dict__}. "
                    f"updated user_shipping_details: {user_shipping_details.__dict__}."
                )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_merge_20230112_1022'),
        ('orders', '0117_auto_20230112_0917'),
    ]

    operations = [
        migrations.RunPython(update_users_shipping_details, reverse_code=migrations.RunPython.noop),
    ]
