# Generated by Django 2.0.5 on 2023-05-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_vacationdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpsettings',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Code used to generate the OTP pass codes'),
        ),
        migrations.AddField(
            model_name='user',
            name='recharge_user_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recharge User ID'),
        ),
    ]
